---
resource_types:
- name: fly-resource
  type: docker-image
  source:
    repository: dexydevdoc/concourse-fly

resources:
  - name: git-repo
    type: git
    source:
      uri: git@github.com:dexyhub/testsubmod.git
      branch: master

jobs:

######################
##  Update Pipeline ##
######################

## Update Pipeline ##
- name: Update-pipeline
  plan:
  - get: git-repo
    trigger: true
  - task: deploy-pipeline
    config:
      platform: linux
      image_resource:
        type: docker-image  
        source: 
          repository: dexydevdoc/concourse-fly
          tag: "1.0"
      inputs:
        - name: git-repo
      run:
        path: /bin/sh
        args: 
        - -exec
        - |
          fly login -t local -c http://127.0.0.1:8080 -u test -p test
          #fly --target local login --team-name main --concourse-url http://127.0.0.1:8080 -u test -p test
          #Deploy pipeline
          echo "Deploying Pipeline"
          fly -t local sp -c git-repo/autodeploypipeline.yml -p autotest
          #fly -t local sp -n -p app-$version -c demo/.ci/pipeline-app.result
          #fly -t local sp -c ~/Desktop/Repos/TED_Portal/ci/pipeline.yml -l ~/Desktop/Repos/TED_Portal/cred.yml -p adebola
          echo "Unpause pipeline after deployment"
          fly -t local unpause-pipeline -p autotest
          #fly -t local up -p app-$version
          echo "Deploment Completed"
          

  

